"""megacompact_core — the real MegaCompact16 simulation engine + verification spine.

The two real files live here as flat modules so that the Kaggle workflow
(``import core as mc`` / ``from engineers import DoublePassEngineerGate``)
works unchanged, while also being importable as a package
(``from megacompact_core import Config``).

core.py      → MegaCompact16 (144 KB): synthetic market generator, time-causal
               feature store, decision-packet builder, AMM / quote / execution /
               cost / outcome simulation, label builder, walk-forward splitter,
               planner, abstention gate, audits, reports, and optional torch
               world-model / FastAPI / Typer CLI paths.

engineers.py → Stationary & Non-Stationary Engineers: the mandatory double-pass
               verification spine (Stationary → Non-Stationary → Stationary)
               with a persistent JSONL VerificationLedger.
"""

# Re-export the engine's public surface (real symbols only).
from .core import (  # noqa: F401
    VERSION,
    SCHEMA_VERSION,
    DEFAULT_CHAIN_ID,
    DEFAULT_BLOCK_TIME_MS,
    EventType,
    Verdict,
    RegimeType,
    ReasonCode,
    set_seed,
    sha256_hash,
    make_pool_update_payload,
    get_reserves,
    SyntheticConfig,
    SplitsConfig,
    ModelConfig,
    CalibrationConfig,
    PlanningConfig,
    ConstraintsConfig,
    OutputConfig,
    Config,
    ArtifactStore,
    JSONLLogger,
    RunManifest,
    NormalizedEvent,
    FeatureValue,
    ActionCandidate,
    DecisionPacket,
    ModelForecast,
    DecisionOutput,
    OutcomeLabel,
    SyntheticMarketGenerator,
    DataValidator,
    TimeCausalFeatureStore,
    DecisionPacketBuilder,
    ConstantProductAMM,
    MarketReplay,
    QuoteEngine,
    ExecutionEngine,
    CostEngine,
    OutcomeEngine,
    LabelBuilder,
    RegimeLabeler,
    WalkForwardSplitter,
    ConformalCalibrator,
    OODDetector,
    RetrievalMemory,
    EmpiricalBaselinePredictor,
    ConstraintEngine,
    ConservativePlanner,
    AbstentionGate,
    PaperBroker,
    Backtester,
    MetricsCalculator,
    StressTestEngine,
    AuditEngine,
    ReportGenerator,
)

from .engineers import (  # noqa: F401
    EngineerVerdict,
    CheckResult,
    EngineerReport,
    DoublePassResult,
    VerificationLedger,
    StationaryEngineer,
    NonStationaryEngineer,
    DoublePassEngineerGate,
)

__all__ = [
    "VERSION",
    "SCHEMA_VERSION",
    "DEFAULT_CHAIN_ID",
    "DEFAULT_BLOCK_TIME_MS",
    "EventType",
    "Verdict",
    "RegimeType",
    "ReasonCode",
    "set_seed",
    "sha256_hash",
    "make_pool_update_payload",
    "get_reserves",
    "SyntheticConfig",
    "SplitsConfig",
    "ModelConfig",
    "CalibrationConfig",
    "PlanningConfig",
    "ConstraintsConfig",
    "OutputConfig",
    "Config",
    "ArtifactStore",
    "JSONLLogger",
    "RunManifest",
    "NormalizedEvent",
    "FeatureValue",
    "ActionCandidate",
    "DecisionPacket",
    "ModelForecast",
    "DecisionOutput",
    "OutcomeLabel",
    "SyntheticMarketGenerator",
    "DataValidator",
    "TimeCausalFeatureStore",
    "DecisionPacketBuilder",
    "ConstantProductAMM",
    "MarketReplay",
    "QuoteEngine",
    "ExecutionEngine",
    "CostEngine",
    "OutcomeEngine",
    "LabelBuilder",
    "RegimeLabeler",
    "WalkForwardSplitter",
    "ConformalCalibrator",
    "OODDetector",
    "RetrievalMemory",
    "EmpiricalBaselinePredictor",
    "ConstraintEngine",
    "ConservativePlanner",
    "AbstentionGate",
    "PaperBroker",
    "Backtester",
    "MetricsCalculator",
    "StressTestEngine",
    "AuditEngine",
    "ReportGenerator",
    "EngineerVerdict",
    "CheckResult",
    "EngineerReport",
    "DoublePassResult",
    "VerificationLedger",
    "StationaryEngineer",
    "NonStationaryEngineer",
    "DoublePassEngineerGate",
]
